# Generated by Django 5.0.14 on 2026-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationhistory',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed allowances (e.g. Housing allowance, Discretionary/Minashi overtime allowance, Role allowance)', max_digits=14),
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='allowances_notes',
            field=models.TextField(blank=True, help_text='Breakdown of fixed allowances (e.g. Housing ¥50k, Discretionary overtime ¥80k)', null=True),
        ),
    ]
