# Generated by Django 5.0.14 on 2026-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_compensationhistory_allowances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationhistory',
            name='commuting_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commuting allowance / 通勤手当', max_digits=14),
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='discretionary_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discretionary work or Minashi fixed overtime allowance / 裁量労働手当 / 固定残業代', max_digits=14),
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Housing allowance / 家賃補助 / 住宅手当', max_digits=14),
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other fixed allowances / その他手当', max_digits=14),
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='remote_work_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remote work / Telework allowance / 在宅勤務手当', max_digits=14),
        ),
        migrations.AddField(
            model_name='compensationhistory',
            name='role_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Role / Management allowance / 役職手当', max_digits=14),
        ),
        migrations.AlterField(
            model_name='compensationhistory',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total fixed allowances (e.g. sum of housing, discretionary overtime, commuting, etc.)', max_digits=14),
        ),
    ]
