# Generated by Django 5.0.14 on 2026-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_compensationhistory_commuting_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayslip',
            name='absent_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Absent / unworked days', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Deposit bank account number e.g. 3016702', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Deposit bank name e.g. Mizuho', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='bank_transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual deposit into bank account', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='discretionary_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discretionary work allowance', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='holiday_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Holiday work hours', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='holiday_work_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Holiday work pay', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='late_night_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Late night hours', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='late_night_overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late night shift allowance', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='loss_of_pay_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='LOP (Loss of pay) days', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='meal_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cafeteria / meal deduction', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='mutual_aid_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mutual aid / benefit society fee', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='pay_period_end',
            field=models.DateField(blank=True, help_text='Pay period end date', null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='pay_period_start',
            field=models.DateField(blank=True, help_text='Pay period start date', null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='remaining_paid_leave_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Remaining annual paid leave balance', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='remote_work_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remote / Telework allowance', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Special / Role allowance', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='std_remuneration_health',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Health insurance standard monthly remuneration', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='std_remuneration_pension',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Welfare pension standard monthly remuneration', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxable base amount for withholding', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total base work hours (e.g. 160.0)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='union_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Labor union dues', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='year_end_tax_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Year-end tax adjustment (+ deduction or - refund)', max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='ytd_gross_pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Year-to-date gross / taxable payment total', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='ytd_income_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Year-to-date income tax deductions total', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='ytd_social_insurance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Year-to-date social insurance deductions total', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base / Job pay', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='commutation_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commuting allowance', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='employment_insurance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employment insurance', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, help_text='Total Gross Pay', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='health_insurance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Health insurance', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Housing / Rent allowance', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='National income tax withheld', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, help_text='Net take-home pay', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='notes',
            field=models.TextField(blank=True, help_text='Communication notes or comments', null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='nursing_insurance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nursing care insurance (age 40+)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other miscellaneous allowances', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Other miscellaneous deductions', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overtime / early-overtime hours', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime / Early-overtime pay', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='paid_leave_days_used',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Paid leave days taken', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Payday date e.g. 2025-10-25', null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Welfare pension insurance', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='resident_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Local inhabitant / resident tax', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='social_insurance_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total social insurance deductions', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, help_text='Total gross deductions', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total taxes withheld', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='working_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Working / payable days', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='year',
            field=models.IntegerField(help_text='Payroll year e.g. 2025'),
        ),
    ]
