# Generated by Django 5.2.4 on 2026-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_monthlypayslip_absent_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayslip',
            name='other_allowances_description',
            field=models.CharField(blank=True, help_text='Description or breakdown of other allowances', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayslip',
            name='other_deductions_description',
            field=models.CharField(blank=True, help_text='Description or breakdown of other deductions', max_length=255, null=True),
        ),
    ]
