# Generated by Django 5.2.4 on 2026-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_monthlypayslip_other_allowances_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to='career_docs/%Y/%m/'),
        ),
    ]
