# Generated by Django 5.2.4 on 2026-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_alter_careerdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdocument',
            name='document_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter (内定通知書 / 採用通知書)'), ('employment_contract', 'Employment Contract / Terms (雇用契約書 / 労働条件通知書)'), ('employment_insurance', 'Employment Insurance Certificate (雇用保険被保険者証)'), ('leaving_certificate', 'Leaving Certificate / Separation (離職票 / 退職証明書)'), ('resignation_acceptance', 'Resignation Acceptance (退職届控 / 退職合意書)'), ('nda', 'NDA / Non-Disclosure Agreement (秘密保持誓約書)'), ('appraisal', 'Appraisal / Performance Review (人事評価・査定書)'), ('recommendation', 'Certificate of Employment / Recommendation (在職証明書 / 推薦状)'), ('visa_document', 'Visa Sponsorship Document (就労ビザ関連書類)'), ('payslip_pdf', 'Monthly Payslip PDF (給与明細書)'), ('bonus_slip_pdf', 'Bonus Statement PDF (賞与明細書)'), ('tax_slip_pdf', 'Withholding Tax Slip PDF (源泉徴収票)'), ('other', 'Other Document (その他)')], default='other', max_length=40),
        ),
    ]
