# Generated by Django 5.2.4 on 2026-10-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_alter_careerdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID / Badge number assigned by employer (e.g. EMP-10294)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured metadata (e.g. manager name, cost center, portal URL, etc.)'),
        ),
        migrations.AddField(
            model_name='employment',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Corporate / work email address assigned for this employment', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayslip',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Deposit bank account number e.g. 1234567', max_length=50, null=True),
        ),
    ]
