runtime: python312
service: backend
env: standard
entrypoint: gunicorn -b :$PORT personalfinance.wsgi:application

handlers:
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "personalfinance.settings.prod"
  APPENGINE_URL: https://backend-dot-personal-finance-425009.uc.r.appspot.com
  PROJECT_ID: 'personal-finance-425009'


runtime_config:
  python_version: 3