runtime: python312
service: backend
version: prod
env: standard
entrypoint: gunicorn -b :$PORT personalfinance.wsgi:application
instance_class : B1

handlers:
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "personalfinance.settings.prod"
  APPENGINE_URL: https://personal-finance-425009.an.r.appspot.com
  PROJECT_ID: 'personal-finance-425009'


runtime_config:
  python_version: 3