# Generated by Django 5.0.2 on 2024-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='stock_currency',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stockpurchasehistory',
            name='stock_currency',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
