# Generated by Django 5.0.2 on 2024-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexfundpurchasehistory',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='indexfundpurchasehistory',
            name='settlement_currency',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stockpurchasehistory',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockpurchasehistory',
            name='settlement_currency',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
