# Generated by Django 5.0.6 on 2024-06-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdailyprice',
            name='year_high_price',
        ),
        migrations.RemoveField(
            model_name='stockdailyprice',
            name='year_low_price',
        ),
    ]
