# Generated by Django 5.0.2 on 2024-04-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_indexfundpurchasehistory_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
