# Generated by Django 5.0.2 on 2024-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_holding_price_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='indexfundpurchasehistory',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockpurchasehistory',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
