# Generated by Django 5.0.2 on 2024-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_forex_alter_indexfundpurchasehistory_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='price_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indexfundpurchasehistory',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockpurchasehistory',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
