# Generated by Django 5.2.4 on 2025-08-13 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(choices=[('transaction', 'Transaction'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('payee', 'Payee'), ('account', 'Account'), ('stock', 'Stock'), ('dividend', 'Dividend')], max_length=50)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('merge', 'Merged'), ('split', 'Split'), ('bulk delete', 'Bulk Deleted')], max_length=50)),
                ('changelog', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
