# Generated by Django 5.2.4 on 2026-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='section',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('payee', 'Payee'), ('account', 'Account')], max_length=50),
        ),
    ]
