

insert into personal_finance.transactions_account (id, account_type, account_name, description, user_id,last_import_date,provider)
values  (1, 'CREDIT_CARD', 'Rakuten Card', null, 1, null, 'Rakuten'),
        (2, 'CREDIT_CARD', 'EPOS Card', null, 1, null, 'EPOS'),
        (3, 'CREDIT_CARD', 'Docomo Card', null, 1, null, 'Docomo'),
        (4, 'BANK_ACCOUNT', 'Mizuho', null, 1, null, 'Mizuho');

#category types
# 1 -> Transaction
# 2 -> Income
# 3 -> Saving
# 4 -> Payment
insert into personal_finance.transactions_transactioncategory (id, category, category_type, description, can_rename, can_delete, user_id)
values  (1, 'Housing', 1, null, true, true, 1),
        (2, 'Transportation', 1, null, true, true, 1),
        (3, 'Food', 1, null, true, true, 1),
        (4, 'Utilities', 1, null, true, true, 1),
        (5, 'Taxes', 1, null, true, true, 1),
        (6, 'Savings', 3, null, true, true, 1),
        (7, 'Entertainment', 1, null, true, true, 1),
        (8, 'Shopping', 1, null, true, true, 1),
        (9, 'Clothing and Accessories', 1, null, true, true, 1),
        (10, 'Personal Care', 1, null, true, true, 1),
        (11, 'Healthcare', 1, null, true, true, 1),
        (12, 'Insurance', 1, null, true, true, 1),
        (13, 'Education', 1, null, true, true, 1),
        (14, 'Cash Payments', 4, null, true, true, 1),
        (15, 'Charitable Giving', 1, null, true, true, 1),
        (16, 'Miscellaneous', 1, null, true, true, 1),
        (17, 'Income', 2, null, true, true, 1);

insert into personal_finance.transactions_transactionsubcategory (id, name, description, can_rename, can_delete, category_id, user_id)
values  (1, 'Mortgage/Rent', null, true, true, 1, 1),
        (2, 'Home/Parking Management fees', null, true, true, 1, 1),
        (3, 'Home Insurance', null, true, true, 1, 1),
        (4, 'Home Repairs/Maintenance', null, true, true, 1, 1),
        (5, 'Car Payment', null, true, true, 2, 1),
        (6, 'Auto Insurance', null, true, true, 2, 1),
        (7, 'Fuel/Gas', null, true, true, 2, 1),
        (8, 'Maintenance/Repairs', null, true, true, 2, 1),
        (9, 'Public Transportation', null, true, true, 2, 1),
        (10, 'Parking', null, true, true, 2, 1),
        (11, 'Tolls', null, true, true, 2, 1),
        (12, 'Car Rental', null, true, true, 2, 1),
        (13, 'Groceries', null, true, true, 3, 1),
        (14, 'Dining Out', null, true, true, 3, 1),
        (15, 'Snacks/Coffee', null, true, true, 3, 1),
        (16, 'Electricity', null, true, true, 4, 1),
        (17, 'Gas', null, true, true, 4, 1),
        (18, 'Water', null, true, true, 4, 1),
        (19, 'Internet', null, true, true, 4, 1),
        (20, 'Phone/Mobile', null, true, true, 4, 1),
        (21, 'Cable/TV', null, true, true, 4, 1),
        (22, 'Income Tax', null, true, true, 5, 1),
        (23, 'Residence Tax', null, true, true, 5, 1),
        (24, 'Property Tax', null, true, true, 5, 1),
        (25, 'Vehicle Tax', null, true, true, 5, 1),
        (26, 'Other', null, true, true, 5, 1),
        (27, 'Emergency Fund', null, true, true, 6, 1),
        (28, 'Investments (Securities)', null, true, true, 6, 1),
        (29, 'Retirement Savings', null, true, true, 6, 1),
        (30, 'Cash Deposits', null, true, true, 6, 1),
        (31, 'Subscriptions', null, true, true, 7, 1),
        (32, 'Movies/Theater/Concerts', null, true, true, 7, 1),
        (33, 'Entrance Tickets', null, true, true, 7, 1),
        (34, 'Hobbies', null, true, true, 7, 1),
        (35, 'Vacations/Travel', null, true, true, 7, 1),
        (36, 'Household Items', null, true, true, 8, 1),
        (37, 'Furniture', null, true, true, 8, 1),
        (38, 'Electronics', null, true, true, 8, 1),
        (39, 'Miscellaneous', null, true, true, 8, 1),
        (40, 'Clothing Purchases', null, true, true, 9, 1),
        (41, 'Shoes Purchases', null, true, true, 9, 1),
        (42, 'Dry Cleaning/Laundry', null, true, true, 9, 1),
        (43, 'Haircuts/Salon', null, true, true, 10, 1),
        (44, 'Cosmetics/Toiletries', null, true, true, 10, 1),
        (45, 'Gym Memberships', null, true, true, 10, 1),
        (46, 'Health Insurance Premiums', null, true, true, 11, 1),
        (47, 'Medical/Dental/Vision Expenses', null, true, true, 11, 1),
        (48, 'Prescriptions/Medications', null, true, true, 11, 1),
        (49, 'Health Club Memberships', null, true, true, 11, 1),
        (50, 'Life Insurance', null, true, true, 12, 1),
        (51, 'Disability Insurance', null, true, true, 12, 1),
        (52, 'Long-Term Care Insurance', null, true, true, 12, 1),
        (53, 'Educational Courses', null, true, true, 13, 1),
        (54, 'Tuition/Fees', null, true, true, 13, 1),
        (55, 'Books/Supplies', null, true, true, 13, 1),
        (56, 'Personal Loan Payments', null, true, true, 14, 1),
        (57, 'Credit Card Payments', null, true, true, 14, 1),
        (58, 'Cash Payments', null, true, true, 14, 1),
        (59, 'Donations to Charities/Organizations', null, true, true, 15, 1),
        (60, 'Gifts', null, true, true, 16, 1),
        (61, 'Pet Expenses', null, true, true, 16, 1),
        (62, 'Bank Fees', null, true, true, 16, 1),
        (63, 'Postal Fees', null, true, true, 16, 1),
        (64, 'Legal/Professional Fees', null, true, true, 16, 1),
        (65, 'Salary/Wages', null, true, true, 17 , 1),
        (66, 'Freelance Income', null, true, true, 17 , 1),
        (67, 'Investment Income', null, true, true, 17 , 1),
        (68, 'Rental Income', null, true, true, 17 , 1),
        (69, 'Side Gig Income', null, true, true, 17 , 1),
        (70, 'Interest Income', null, true, true, 17 , 1),
        (71, 'Bonus/Commission', null, true, true, 17 , 1),
        (72, 'Gifts/Donations', null, true, true, 17 , 1),
        (73, 'Government Assistance', null, true, true, 17 , 1),
        (74, 'Other', null, true, true, 17 , 1);

INSERT INTO investments_companysector (id, name, created_at, modified_at) VALUES
(1, 'Basic Materials', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Communication Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Consumer Cyclical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Consumer Defensive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Energy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Financial Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Healthcare', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Industrials', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'Real Estate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'Technology', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'Utilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO investments_companyindustry (id, name, created_at, modified_at) VALUES
(1, 'Steel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'Silver', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'Other Precious Metals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'Gold', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'Copper', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'Aluminum', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'Paper, Lumber & Forest Products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'Industrial Materials', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'Construction Materials', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'Chemicals - Specialty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'Chemicals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'Agricultural Inputs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'Telecommunications Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'Internet Content & Information', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'Publishing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'Broadcasting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'Advertising Agencies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'Entertainment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'Travel Lodging', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 'Travel Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 'Specialty Retail', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 'Luxury Goods', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 'Home Improvement', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 'Residential Construction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 'Department Stores', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 'Personal Products & Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 'Leisure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 'Gambling, Resorts & Casinos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 'Furnishings, Fixtures & Appliances', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 'Restaurants', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 'Auto - Parts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 'Auto - Manufacturers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 'Auto - Recreational Vehicles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 'Auto - Dealerships', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 'Apparel - Retail', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 'Apparel - Manufacturers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 'Apparel - Footwear & Accessories', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 'Packaging & Containers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 'Tobacco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 'Grocery Stores', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 'Discount Stores', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 'Household & Personal Products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 'Packaged Foods', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 'Food Distribution', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 'Food Confectioners', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 'Agricultural Farm Products', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 'Education & Training Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 'Beverages - Wineries & Distilleries', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 'Beverages - Non-Alcoholic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 'Beverages - Alcoholic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(51, 'Uranium', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 'Solar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(53, 'Oil & Gas Refining & Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 'Oil & Gas Midstream', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(55, 'Oil & Gas Integrated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 'Oil & Gas Exploration & Production', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(57, 'Oil & Gas Equipment & Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(58, 'Oil & Gas Energy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 'Oil & Gas Drilling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(60, 'Coal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(61, 'Shell Companies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(62, 'Investment - Banking & Investment Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(63, 'Insurance - Specialty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(64, 'Insurance - Reinsurance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(65, 'Insurance - Property & Casualty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(66, 'Insurance - Life', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(67, 'Insurance - Diversified', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(68, 'Insurance - Brokers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(69, 'Financial - Mortgages', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(70, 'Financial - Diversified', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(71, 'Financial - Data & Stock Exchanges', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(72, 'Financial - Credit Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(73, 'Financial - Conglomerates', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(74, 'Financial - Capital Markets', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(75, 'Banks - Regional', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(76, 'Banks - Diversified', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(77, 'Banks', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(78, 'Asset Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(79, 'Asset Management - Bonds', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(80, 'Asset Management - Income', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(81, 'Asset Management - Leveraged', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(82, 'Asset Management - Cryptocurrency', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(83, 'Asset Management - Global', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(84, 'Medical - Specialties', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(85, 'Medical - Pharmaceuticals', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(86, 'Medical - Instruments & Supplies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(87, 'Medical - Healthcare Plans', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(88, 'Medical - Healthcare Information Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(89, 'Medical - Equipment & Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(90, 'Medical - Distribution', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(91, 'Medical - Diagnostics & Research', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(92, 'Medical - Devices', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(93, 'Medical - Care Facilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(94, 'Drug Manufacturers - Specialty & Generic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(95, 'Drug Manufacturers - General', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(96, 'Biotechnology', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(97, 'Waste Management', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(98, 'Trucking', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(99, 'Railroads', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100, 'Aerospace & Defense', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(101, 'Marine Shipping', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 'Integrated Freight & Logistics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 'Airlines, Airports & Air Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 'General Transportation', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 'Manufacturing - Tools & Accessories', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(106, 'Manufacturing - Textiles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(107, 'Manufacturing - Miscellaneous', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(108, 'Manufacturing - Metal Fabrication', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(109, 'Industrial - Distribution', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110, 'Industrial - Specialties', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(111, 'Industrial - Pollution & Treatment Controls', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(112, 'Environmental Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(113, 'Industrial - Machinery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(114, 'Industrial - Infrastructure Operations', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(115, 'Industrial - Capital Goods', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(116, 'Consulting Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(117, 'Business Equipment & Supplies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(118, 'Staffing & Employment Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(119, 'Rental & Leasing Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120, 'Engineering & Construction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(121, 'Security & Protection Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(122, 'Specialty Business Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(123, 'Construction', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(124, 'Conglomerates', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(125, 'Electrical Equipment & Parts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(126, 'Agricultural - Machinery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(127, 'Agricultural - Commodities/Milling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(128, 'REIT - Specialty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(129, 'REIT - Retail', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130, 'REIT - Residential', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(131, 'REIT - Office', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(132, 'REIT - Mortgage', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(133, 'REIT - Industrial', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(134, 'REIT - Hotel & Motel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(135, 'REIT - Healthcare Facilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(136, 'REIT - Diversified', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(137, 'Real Estate - Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(138, 'Real Estate - Diversified', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(139, 'Real Estate - Development', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140, 'Real Estate - General', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(141, 'Information Technology Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(142, 'Hardware, Equipment & Parts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(143, 'Computer Hardware', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(144, 'Electronic Gaming & Multimedia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(145, 'Software - Services', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(146, 'Software - Infrastructure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(147, 'Software - Application', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(148, 'Semiconductors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(149, 'Media & Entertainment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(150, 'Communication Equipment', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(151, 'Technology Distributors', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(152, 'Consumer Electronics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(153, 'Renewable Utilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(154, 'Regulated Water', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(155, 'Regulated Gas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(156, 'Regulated Electric', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(157, 'Independent Power Producers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(158, 'Diversified Utilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(159, 'General Utilities', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
