"""
Django settings for personalfinance project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import io
import logging
import os
from datetime import timedelta
from pathlib import Path

from decouple import config
from dotenv import dotenv_values

BASE_DIR = Path(__file__).resolve().parent.parent

ENV = config("ENV", default="dev")
IS_PROD = ENV == 'prod'
DEBUG = config('DEBUG', default=False, cast=bool)

# Support direct environment variables (recommended for Cloud Run) with optional Secret Manager
USE_SECRET_MANAGER = config('USE_SECRET_MANAGER', default=False, cast=bool)
if USE_SECRET_MANAGER:
    try:
        from google.cloud import secretmanager
        gcloud_project = (
            config('GOOGLE_CLOUD_PROJECT', default=None)
            or config('GCP_PROJECT', default=None)
            or os.environ.get('CLOUDSDK_CORE_PROJECT')
        )
        if gcloud_project:
            client = secretmanager.SecretManagerServiceClient()
            secret_name = config('DJANGO_SECRET_NAME', default='django_settings')
            name = f'projects/{gcloud_project}/secrets/{secret_name}/versions/latest'
            response = client.access_secret_version(name=name)
            secret = response.payload.data.decode('UTF-8')
            env_vars = dotenv_values(stream=io.StringIO(secret))
            os.environ.update(env_vars)
    except Exception as e:
        logging.warning("Could not fetch secret from Secret Manager: %s. Using environment variables.", e)
else:
    local_env = os.path.join(BASE_DIR, '.env')
    if os.path.exists(local_env):
        env_vars = dotenv_values(local_env)
        for k, v in env_vars.items():
            if k not in os.environ and v is not None:
                os.environ[k] = v

# Cloud Run / Proxy SSL Configuration
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = IS_PROD

allowed_hosts_str = config('ALLOWED_HOSTS', default=config('ALLOWED_HOST', default='*'))
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]
if DEBUG and '*' not in ALLOWED_HOSTS:
    for h in ['localhost', '127.0.0.1', 'testserver']:
        if h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(h)

csrf_origins_str = config('CSRF_TRUSTED_ORIGINS', default='https://*.run.app,https://*.appspot.com')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in csrf_origins_str.split(',') if o.strip()]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'djoser',
    "oauth",
    "changelog",
    "accounts",
    "finance.transactions",
    "finance.categories",
    "finance.payees",
    "finance.settings",
    "finance.career",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth.middleware.ThreadLocalMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'] + ([CLIENT_DIST_DIR] if 'CLIENT_DIST_DIR' in locals() and os.path.exists(CLIENT_DIST_DIR) else []),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Single Page Application (React/Vite) client bundle location
CLIENT_DIST_DIR = os.path.join(BASE_DIR, 'client_dist')
DEV_CLIENT_DIST = os.path.join(BASE_DIR.parent, 'personalfinance-web', 'dist')
if not os.path.exists(CLIENT_DIST_DIR) and os.path.exists(DEV_CLIENT_DIST):
    CLIENT_DIST_DIR = DEV_CLIENT_DIST

# WhiteNoise configuration to serve static frontend files from root / (e.g. /assets/...)
if os.path.exists(CLIENT_DIST_DIR):
    WHITENOISE_ROOT = CLIENT_DIST_DIR

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

db_host = config('DB_HOST', default=None)
if not db_host or db_host in ('127.0.0.1', 'localhost'):
    # In Cloud Run, Cloud SQL instances are mounted under /cloudsql/<PROJECT:REGION:INSTANCE>
    cloudsql_dir = Path('/cloudsql')
    if cloudsql_dir.exists():
        sockets = [str(p) for p in cloudsql_dir.iterdir() if p.name.count(':') >= 2 or (p.is_dir() and not p.name.startswith('.'))]
        if sockets:
            db_host = sockets[0]
            logging.info("Auto-detected Cloud SQL Unix socket: %s", db_host)

if not db_host:
    db_host = '127.0.0.1'

db_config = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': config('DB_NAME', default='personalfinance'),
    'USER': config('DB_USER', default='root'),
    'PASSWORD': config('DB_PASSWORD', default=''),
    'HOST': db_host,
}
db_port = config('DB_PORT', default=None)
if db_port and str(db_port).strip().lower() not in ('none', '', 'null') and not db_host.startswith('/'):
    db_config['PORT'] = str(db_port).strip()

DATABASES = {
    'default': db_config
}
SECRET_KEY = config('SECRET_KEY')

BUCKET_NAME = config('BUCKET_NAME', default=None)

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

AUTH_USER_MODEL = "oauth.User"

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=config('JWT_ACCESS_TOKEN_LIFETIME_DAYS', default=30 if not IS_PROD else 1, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=365, cast=int)),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': SECRET_KEY,
    'TOKEN_OBTAIN_SERIALIZER': "oauth.serializers.TokenObtainPairSerializer",
}

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'oauth.serializers.UserCreateSerializer',
    },
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
}

INTERNAL_IPS = [
    "127.0.0.1",
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'https://personal-finance-425009.uc.r.appspot.com',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
