"""
Django settings for personalfinance project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import io
import logging
import os
from datetime import timedelta
from pathlib import Path

from decouple import config
from google.cloud import secretmanager
from dotenv import dotenv_values

BASE_DIR = Path(__file__).resolve().parent.parent

ENV = config("ENV", default="dev")
IS_PROD = ENV == 'prod'
DEBUG = config('DEBUG', default=False, cast=bool)
if IS_PROD:
    # google app engine inject GOOGLE_CLOUD_PROJECT and app.yaml environment variable on production
    def get_gcp_secret():
        """
        Fetches a secret from Google Cloud Secret Manager.
        """
        gcloud_project = config('GOOGLE_CLOUD_PROJECT', None)
        if not gcloud_project:
            raise ValueError("PROJECT_ID is not set in the environment variables.")

        client = secretmanager.SecretManagerServiceClient()
        secret_name = config('DJANGO_SECRET_NAME', 'django_settings')
        name = f'projects/{gcloud_project}/secrets/{secret_name}/versions/latest'
        response = client.access_secret_version(name=name)
        return response.payload.data.decode('UTF-8')

    secret = get_gcp_secret()
    env_vars = dotenv_values(stream=io.StringIO(secret))
    os.environ.update(env_vars)

else:
    local_env = os.path.join(BASE_DIR, '.env')
    if os.path.exists(local_env):
        env_vars = dotenv_values(local_env)
        os.environ.update(env_vars)

ALLOWED_HOSTS = [config('ALLOWED_HOST')]
CSRF_TRUSTED_ORIGINS = [config('CSRF_TRUSTED_ORIGINS')]
SECURE_SSL_REDIRECT = IS_PROD

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'djoser',
    "oauth",
    "changelog",
    "accounts",
    "finance.transactions",
    "finance.categories",
    "finance.payees",
    "finance.reporting",
    "finance.settings",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth.middleware.ThreadLocalMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'personalfinance/media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'HOST': config('DB_HOST'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
    }
}
SECRET_KEY = config('SECRET_KEY')

BUCKET_NAME = config('BUCKET_NAME', default=None)

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

AUTH_USER_MODEL = "oauth.User"

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': SECRET_KEY,
    'TOKEN_OBTAIN_SERIALIZER': "oauth.serializers.TokenObtainPairSerializer",
}

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'oauth.serializers.UserCreateSerializer',
    },
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
}

INTERNAL_IPS = [
    "127.0.0.1",
]

CORS_ALLOWED_ORIGINS = ['http://localhost:5173', 'https://personal-finance-425009.uc.r.appspot.com']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # 'file': {
        #     'class': 'logging.FileHandler',
        #     'filename': 'general.log'
        # }
    },
    'loggers': {
        'django.db.backends': {
        }
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} - ({levelname}) - {name} - {message}',
            'style': '{'
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    }
}
