# Generated by Django 5.0.6 on 2024-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewriteRules',
        ),
        migrations.AddField(
            model_name='destinationmap',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
