# Generated by Django 5.0.6 on 2024-09-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmap',
            name='category_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationmap',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
