# Generated by Django 5.0.6 on 2024-09-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_destinationmap_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationmap',
            name='transaction_type',
        ),
    ]
