# Generated by Django 5.0.6 on 2024-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_destinationmap_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_import_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ImportRules',
        ),
    ]
