# Generated by Django 5.0.6 on 2024-09-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_importrules_modified_at_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
