# Generated by Django 5.2.4 on 2025-07-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('english_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investments_fund',
            },
        ),
        migrations.CreateModel(
            name='FundPurchaseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('settlement_currency', models.CharField(blank=True, max_length=12, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investments_fund_purchase_history',
            },
        ),
        migrations.CreateModel(
            name='FundDailyPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index_fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fund.fund')),
            ],
            options={
                'db_table': 'investments_fund_daily_price',
            },
        ),
        migrations.CreateModel(
            name='FundHolding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fund_currency', models.CharField(blank=True, max_length=12, null=True)),
                ('price_updated_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
            ],
            options={
                'db_table': 'investments_fund_holding',
            },
        ),
    ]
