TRANSACTION_DATA_FOLDER = 'finance'

LOCAL_STORAGE = 'local_storage'
GOOGLE_CLOUD_STORAGE = 'google_cloud_storage'

ACCOUNT_TYPE_CREDIT_CARD = 'CREDIT_CARD'
ACCOUNT_TYPE_BANK_ACCOUNT = 'BANK_ACCOUNT'
ACCOUNT_TYPE_INVESTMENT_ACCOUNT = 'INVESTMENT_ACCOUNT'

CREDIT_CARD_PROVIDER_RAKUTEN = 'Rakuten'
CREDIT_CARD_PROVIDER_EPOS = 'EPOS'
CREDIT_CARD_PROVIDER_DOCOMO = 'Docomo'
BANK_ACCOUNT_PROVIDER_MIZUHO = 'Mizuho'
BANK_ACCOUNT_PROVIDER_JP_POST = 'JP POST'
INVESTMENT_ACCOUNT_PROVIDER_RAKUTEN = 'Rakuten'
