
EXPENSE_CATEGORY_TYPE = 1
INCOME_CATEGORY_TYPE = 2
SAVINGS_CATEGORY_TYPE = 3
PAYMENT_CATEGORY_TYPE = 4

TRANSACTION_CATEGORY_TEXT = 'TRANSACTION'
INCOME_CATEGORY_TEXT = 'INCOME'
SAVINGS_CATEGORY_TEXT = 'SAVINGS'
PAYMENT_CATEGORY_TEXT = 'PAYMENT'

ACCOUNT_PROVIDER_RAKUTEN = 'Rakuten'
ACCOUNT_PROVIDER_EPOS_CARD = 'EPOS'
ACCOUNT_PROVIDER_DOCOMO_CARD = 'Docomo'
ACCOUNT_PROVIDER_MIZUHO = 'Mizuho'

EPOS_CARD_ELECTRONIC_SIGNATURES = ['／Ｎ', '／ＮＦＣ', 'ＡＰ／', '／ＮＦＣ ()', '／ＮＦＣ', '	ＡＰ／']
DOCOMO_CARD_ELECTRONIC_SIGNATURES = ['／ｉＤ', 'ｉＤ／', '　／ｉＤ', 'ｉＤ／', '　　　　　　　　　／ｉＤ', '　／ｉＤ']
RAKUTEN_CARD_ELECTRONIC_SIGNATURES = ['楽天ＳＰ', '/N']