# Generated by Django 5.0.6 on 2024-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
