# Generated by Django 5.2.4 on 2025-07-27 09:12

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('goal', models.CharField(blank=True, max_length=50, null=True)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_portfolio',
            },
        ),
        migrations.CreateModel(
            name='PortfolioDailyGrowth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('portfolio_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_return', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'investments_portfolio_daily_growth',
            },
            managers=[
                ('cron_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
