NA_TRANSACTION_CATEGORY_ID = 1000
NA_TRANSACTION_SUB_CATEGORY_ID = 1000
OTHER_INCOME_CATEGORY_ID = 10
SAVINGS_CATEGORY_ID = 6
PAYMENT_CATEGORY_ID = 14

EPOS_CARD_ELECTRONIC_SIGNATURES = ['／Ｎ', '／ＮＦＣ', 'ＡＰ／', '／ＮＦＣ ()', '／ＮＦＣ', '	ＡＰ／']
DOCOMO_CARD_ELECTRONIC_SIGNATURES = ['／ｉＤ', 'ｉＤ／', '　／ｉＤ', 'ｉＤ／', '　　　　　　　　　／ｉＤ', '　／ｉＤ']
RAKUTEN_CARD_ELECTRONIC_SIGNATURES = ['楽天ＳＰ', '/N']